[tool.poetry]
name = "django-learn"
version = "0.1.0"
description = ""
authors = ["Akshay"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
Django = "^5.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
